contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #pipeline channel"
    url: https://nfcore.slack.com/channels/pipeline
    about: Discussion about the nf-core/pipeline pipeline
